# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1f051c65a29b3e6ea701c6fdbac0e19f132c9851f68600f823987b17b113aff525d08877837b9d6c4d35fdedc647bce9c3d26fd2146458ee0ed8acfdbff9047

test:
  secret_key_base: 34e48af663ce4bd05170a1332d5657ac63aad5408b8ae413b8b09e5a11ad2457da58d51c5ac47040e3b0c00683ffe61c85a3490724cca6d734af9b2a073a05a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
